version: '3.2'

services:
  tracker-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx/idsr:2.0.0
   # ports:
   #     - "4205:80"
    restart: always
  db-tracker:
    image: postgres:10.12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - 5433:5432
    volumes:
      - idsr-tracker-data:/var/lib/postgresql/data
  ussd-tracker-1:
    image: node:10.18.1-alpine3.11
    working_dir: /home/app
    command: npm run start_all
    restart: always
    ports:
        - "4205:3021"
    volumes:
      - type: bind
        source: ./
        target: /home/app/
    deploy:
      replicas: 1
volumes:
  idsr-tracker-data:
    driver: local
